/* Admin dashboard prototype. No backend actions are executed. */
(function () {
  'use strict';
  const users = [
    { id:'u1', name:'Aanya Sharma', email:'aanya@example.com', city:'New Delhi', joined:'12 Jul 2026', status:'verified', activity:'Active now', initials:'AS' },
    { id:'u2', name:'Rohan Mehta', email:'rohan@example.com', city:'Mumbai', joined:'10 Jul 2026', status:'verified', activity:'12 min ago', initials:'RM' },
    { id:'u3', name:'Meera Iyer', email:'meera@example.com', city:'Bengaluru', joined:'08 Jul 2026', status:'pending', activity:'1 hr ago', initials:'MI' },
    { id:'u4', name:'Kabir Singh', email:'kabir@example.com', city:'Chandigarh', joined:'06 Jul 2026', status:'suspended', activity:'2 days ago', initials:'KS' },
    { id:'u5', name:'Vihaan Kapoor', email:'vihaan@example.com', city:'New Delhi', joined:'03 Jul 2026', status:'pending', activity:'Yesterday', initials:'VK' }
  ];
  const reports = [
    { id:'r1', type:'message', subject:'Message report from Aanya Sharma', detail:'Reported for language that felt disrespectful in a private conversation.', time:'12 min ago', priority:'High' },
    { id:'r2', type:'profile', subject:'Profile review: incomplete information', detail:'A member flagged an inconsistency between profile details and uploaded images.', time:'38 min ago', priority:'Medium' },
    { id:'r3', type:'content', subject:'Community post requires moderation', detail:'A discussion comment was reported by two community members.', time:'1 hr ago', priority:'Medium' },
    { id:'r4', type:'message', subject:'Message report from Meera Iyer', detail:'Reported a conversation for repeated unsolicited messages.', time:'Yesterday', priority:'High' }
  ];
  const profileReviews = [
    { id:'p1', name:'Meera Iyer', initials:'MI', city:'Bengaluru', notes:['Profile photo uploaded','Bio complete','Mobile pending'] },
    { id:'p2', name:'Neel Shah', initials:'NS', city:'Ahmedabad', notes:['Profile photo uploaded','Education provided','Review preferences'] },
    { id:'p3', name:'Tanya Kapoor', initials:'TK', city:'Pune', notes:['Bio complete','Identity submitted','Mobile pending'] }
  ];
  const state = { view:'overview', userQuery:'', userStatus:'all', reportFilter:'all', pendingAction:null };
  const $ = (selector, scope=document) => scope.querySelector(selector); const $$ = (selector, scope=document) => Array.from(scope.querySelectorAll(selector)); let toastTimer;
  function toast(message){const target=$('#admin-toast');target.textContent=message;target.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>target.classList.remove('show'),3000)}
  function setView(view){state.view=view;$$('.admin-view').forEach((section)=>section.classList.toggle('active',section.dataset.adminSection===view));$$('.admin-nav-item').forEach((button)=>button.classList.toggle('active',button.dataset.adminView===view));$('#admin-sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
  function activityMarkup(){return ['New mutual match created','Profile review submitted','Community post approved','Report resolved'].map((item,index)=>`<li><i class="activity-icon">${['♡','✓','✦','⚑'][index]}</i><div><strong>${item}</strong><span>${['Rohan and Aanya started a conversation.','Meera Iyer joined the profile queue.','A relationship tip reached 1,200 members.','A message report was closed with a warning.'][index]}</span></div><time>${['Now','8m','24m','41m'][index]}</time></li>`).join('')}
  function reviewQueueMarkup(){return reports.slice(0,3).map((report)=>`<div class="review-row"><i class="review-icon">${report.type==='message'?'✉':report.type==='profile'?'◉':'✦'}</i><div><strong>${report.subject}</strong><span>${report.priority} priority · ${report.time}</span></div><button type="button" data-admin-view="reports">Review</button></div>`).join('')}
  function renderUsers(){const term=state.userQuery.toLowerCase();const filtered=users.filter((user)=>(state.userStatus==='all'||user.status===state.userStatus)&&`${user.name} ${user.email} ${user.city}`.toLowerCase().includes(term));$('#users-table-body').innerHTML=filtered.map((user)=>`<tr data-user-id="${user.id}"><td><div class="member-cell"><span class="member-initials">${user.initials}</span><div><strong>${user.name}</strong><span>${user.email}</span></div></div></td><td>${user.city}</td><td>${user.joined}</td><td><span class="admin-status status-${user.status}">${user.status}</span></td><td>${user.activity}</td><td><div class="user-actions"><button type="button" data-user-action="verify">Verify</button><button type="button" data-user-action="suspend">Suspend</button><button class="danger" type="button" data-user-action="delete">Delete</button></div></td></tr>`).join('');$('#user-table-summary').textContent=`Showing ${filtered.length} of ${users.length} users`;}
  function renderReports(){const filtered=reports.filter((report)=>state.reportFilter==='all'||report.type===state.reportFilter);$('#reports-grid').innerHTML=filtered.map((report)=>`<article class="report-card" data-report-id="${report.id}"><header class="report-card-head"><strong>${report.subject}</strong><span>${report.type} · ${report.priority}</span></header><p>${report.detail}</p><footer><small>${report.time}</small><button type="button" data-report-action="review">Review report</button></footer></article>`).join('');$('#report-count').textContent=reports.length;$('#open-report-metric').textContent=reports.length;}
  function renderModeration(){const messageReports=reports.filter((report)=>report.type==='message');$('#message-reports').innerHTML=messageReports.map((report)=>`<div class="moderation-row"><i class="review-icon">✉</i><div><strong>${report.subject}</strong><span>${report.detail}</span></div><button type="button" data-report-action="review" data-report-id="${report.id}">Open</button></div>`).join('');$('#community-moderation').innerHTML=['Comment reported in “First conversations”','Event description needs review','Community post awaiting approval'].map((label,index)=>`<div class="moderation-row"><i class="review-icon">✦</i><div><strong>${label}</strong><span>${['Two reports · 1 hour ago','Policy check · Today','New submission · 2 hours ago'][index]}</span></div><button type="button" data-content-action="review">Review</button></div>`).join('');}
  function renderProfiles(){ $('#profile-review-grid').innerHTML=profileReviews.map((profile)=>`<article class="profile-review-card" data-profile-review-id="${profile.id}"><span class="member-initials">${profile.initials}</span><h2>${profile.name}</h2><p>${profile.city} · Submitted today</p><ul>${profile.notes.map((note)=>`<li>${note}</li>`).join('')}</ul><footer><button class="accept" type="button" data-profile-action="approve">Approve</button><button type="button" data-profile-action="review">Review</button></footer></article>`).join('');$('#profile-review-count').textContent=profileReviews.length;}
  function renderContent(){ $('#content-queue').innerHTML=['Relationship tip: “Questions that build trust”','Community discussion: “Balancing family and individuality”','Virtual event: “Ask a matchmaker”'].map((item,index)=>`<div class="content-row"><i class="review-icon">${['▤','◌','◷'][index]}</i><div><strong>${item}</strong><span>${['Draft · Submitted today','Comment activity · 3 reports','Event listing · Scheduled 18 Aug'][index]}</span></div><button type="button" data-content-action="review">Review</button></div>`).join('');}
  function openConfirm(action, detail){state.pendingAction={action,detail};$('#admin-confirm-title').textContent=`${action} this record?`;$('#admin-confirm-copy').textContent=detail;$('#admin-confirm').hidden=false}
  function closeConfirm(){state.pendingAction=null;$('#admin-confirm').hidden=true}
  function initialise(){ $('#activity-list').innerHTML=activityMarkup();$('#review-queue').innerHTML=reviewQueueMarkup();renderUsers();renderReports();renderModeration();renderProfiles();renderContent();$$('.admin-nav-item').forEach((button)=>button.addEventListener('click',()=>setView(button.dataset.adminView)));$$('[data-admin-view]').forEach((button)=>{if(!button.classList.contains('admin-nav-item'))button.addEventListener('click',()=>setView(button.dataset.adminView))});$('#user-search-input').addEventListener('input',(event)=>{state.userQuery=event.target.value;renderUsers()});$('#user-status-filter').addEventListener('change',(event)=>{state.userStatus=event.target.value;renderUsers()});$('#users-table-body').addEventListener('click',(event)=>{const button=event.target.closest('[data-user-action]');if(!button)return;const user=users.find((item)=>item.id===button.closest('[data-user-id]').dataset.userId);openConfirm(button.dataset.userAction,`${button.dataset.userAction} action for ${user.name}. This demonstration will only update local state.`)});$$('.report-filter').forEach((button)=>button.addEventListener('click',()=>{state.reportFilter=button.dataset.reportFilter;$$('.report-filter').forEach((item)=>item.classList.toggle('active',item===button));renderReports()}));$('#reports-grid').addEventListener('click',(event)=>{if(event.target.closest('[data-report-action]'))toast('Report opened in this local moderation preview.')});$('#admin-confirm-cancel').addEventListener('click',closeConfirm);$('#admin-confirm-continue').addEventListener('click',()=>{const action=state.pendingAction?.action;closeConfirm();toast(`${action} action recorded locally. Connect an admin API to apply it.`)});$('#admin-menu').addEventListener('click',()=>$('#admin-sidebar').classList.toggle('open'));$$('[data-admin-action]').forEach((button)=>button.addEventListener('click',()=>toast(`${button.dataset.adminAction.replaceAll('-',' ')} is ready for an admin backend.`)));$$('[data-profile-action],[data-content-action]').forEach((button)=>button.addEventListener('click',()=>toast('Review action is ready for the moderation workflow.')));}
  window.adminDataAdapter={getAnalyticsQuery(){return{tables:['profiles','match_actions','messages','reports'],metrics:['growth','daily_active_users','mutual_matches','open_reports']};},getUserQuery(filters){return{table:'profiles',select:'id, full_name, email, city, status, created_at, last_active_at',filters};},getAdminAction(userId,action){return{table:'admin_actions',values:{target_user_id:userId,action}};},getReportQueue(){return{table:'reports',select:'id, reporter_id, target_id, category, reason, status, created_at',filters:{status:'open'}};},getModerationAction(contentId,action){return{table:'moderation_actions',values:{content_id:contentId,action}};}};
  initialise();
}());
