/* Live support inbox. This page requires an authenticated user with app_metadata.role = "admin". */
(function () {
  'use strict';
  const api = window.ManglikSupabase; const $ = (selector) => document.querySelector(selector);
  const state = { messages: [], selected: null, query: '', status: 'all', user: null, channel: null };
  const escape = (value) => String(value || '').replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' })[char]);
  const toast = (message) => { const node = $('#contact-admin-toast'); node.textContent = message; node.classList.add('show'); clearTimeout(node._timer); node._timer = setTimeout(() => node.classList.remove('show'), 3600); };
  const stamp = (value) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
  const initials = (name) => String(name || '?').split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  const visible = () => state.messages.filter((item) => (state.status === 'all' || item.status === state.status) && (!state.query || `${item.name} ${item.email} ${item.subject} ${item.message}`.toLowerCase().includes(state.query)));
  function renderList() { const items = visible(); $('#contact-inbox-loading').hidden = true; $('#contact-inbox-list').innerHTML = items.map((item) => `<article class="contact-row ${item.status === 'new' ? 'unread' : ''} ${state.selected?.id === item.id ? 'active' : ''}" data-contact-id="${item.id}"><span class="contact-row-avatar">${escape(initials(item.name))}</span><div class="contact-row-copy"><strong>${escape(item.name)}</strong><span>${escape(item.subject)}</span><small>${escape(item.email)} · ${stamp(item.created_at)}</small></div><b class="contact-status ${escape(item.status)}">${escape(item.status.replace('_', ' '))}</b></article>`).join(''); $('#contact-inbox-empty').hidden = items.length !== 0; $('#contact-inbox-summary').textContent = `${items.length} message${items.length === 1 ? '' : 's'}`; $('#contact-unread-count').textContent = state.messages.filter((item) => item.status === 'new').length; }
  function renderDetail() { const panel = $('#contact-detail-panel'); const item = state.selected; if (!item) { panel.innerHTML = '<div class="contact-detail-empty"><span>✉</span><h2>Select a message</h2><p>Read the full note, send a reply, or update its status.</p></div>'; return; } panel.innerHTML = `<div class="contact-detail-content"><header class="contact-detail-head"><div><p class="contact-panel-head">Support message</p><h2>${escape(item.subject)}</h2><p class="contact-detail-meta">From <strong>${escape(item.name)}</strong> · <a href="mailto:${encodeURIComponent(item.email)}">${escape(item.email)}</a><br>Received ${stamp(item.created_at)}</p></div><b class="contact-status ${escape(item.status)}">${escape(item.status.replace('_', ' '))}</b></header><article class="contact-detail-message">${escape(item.message)}</article><div class="contact-detail-actions"><button type="button" data-contact-action="in_progress">Mark in progress</button><button type="button" data-contact-action="resolved">Mark resolved</button><button type="button" data-contact-action="archived">Archive</button><button class="danger" type="button" data-contact-action="delete">Delete</button></div><form class="contact-reply-form" id="contact-reply-form"><label for="contact-reply">Reply to ${escape(item.name)}</label><textarea id="contact-reply" minlength="2" maxlength="4000" required placeholder="Write a clear, caring response…"></textarea><footer><small>Replies are emailed securely through Resend.</small><button type="submit">Send reply</button></footer></form></div>`; }
  async function load() { $('#contact-inbox-loading').hidden = false; try { const { data, error } = await api.client.from('contact_messages').select('*').order('created_at', { ascending: false }); if (error) throw error; state.messages = data || []; if (state.selected) state.selected = state.messages.find((item) => item.id === state.selected.id) || null; renderList(); renderDetail(); } catch (error) { $('#contact-inbox-loading').textContent = `Unable to load the inbox: ${error.message}`; $('#contact-inbox-loading').hidden = false; } }
  async function update(id, status) { try { const { error } = await api.client.from('contact_messages').update({ status }).eq('id', id); if (error) throw error; await load(); toast(status === 'archived' ? 'Message archived.' : `Message marked ${status.replace('_', ' ')}.`); } catch (error) { toast(`Could not update message: ${error.message}`); } }
  async function remove(id) { if (!window.confirm('Delete this support message permanently?')) return; try { const { error } = await api.client.from('contact_messages').delete().eq('id', id); if (error) throw error; state.selected = null; await load(); toast('Message deleted.'); } catch (error) { toast(`Could not delete message: ${error.message}`); } }
  async function reply(event) { event.preventDefault(); const replyText = $('#contact-reply').value.trim(); if (replyText.length < 2) return; const button = event.currentTarget.querySelector('button[type="submit"]'); button.disabled = true; button.textContent = 'Sending…'; try { const session = await window.ManglikAuth.start(); const response = await fetch('/.netlify/functions/contact-reply', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ id: state.selected.id, reply: replyText }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error?.message || 'Reply failed.'); await load(); toast('Reply sent and message resolved.'); } catch (error) { toast(error.message); } finally { button.disabled = false; button.textContent = 'Send reply'; } }
  async function initialise() { try { await window.ManglikAuth.start(); state.user = await api.requireUser(); if (state.user.app_metadata?.role !== 'admin') throw new Error('This inbox is available to support administrators only.'); await load(); state.channel = api.client.channel('admin-contact-inbox').on('postgres_changes', { event: '*', schema: 'public', table: 'contact_messages' }, load).subscribe(); } catch (error) { $('#contact-inbox-loading').textContent = error.message; $('#contact-inbox-loading').hidden = false; } }
  $('#contact-inbox-search').addEventListener('input', (event) => { state.query = event.target.value.trim().toLowerCase(); renderList(); }); $('#contact-status-filter').addEventListener('change', (event) => { state.status = event.target.value; renderList(); }); $('#refresh-contact-inbox').addEventListener('click', load); $('#contact-inbox-list').addEventListener('click', (event) => { const row = event.target.closest('[data-contact-id]'); if (!row) return; state.selected = state.messages.find((item) => item.id === row.dataset.contactId) || null; renderList(); renderDetail(); }); $('#contact-detail-panel').addEventListener('click', (event) => { const action = event.target.closest('[data-contact-action]'); if (!action || !state.selected) return; if (action.dataset.contactAction === 'delete') remove(state.selected.id); else update(state.selected.id, action.dataset.contactAction); }); $('#contact-detail-panel').addEventListener('submit', (event) => { if (event.target.id === 'contact-reply-form') reply(event); }); $('#contact-admin-menu').addEventListener('click', () => $('#contact-admin-sidebar').classList.toggle('open'));
  initialise();
}());
