/* Local Matches module with a Supabase-ready backend contract. */
(function () {
  'use strict';
  if (window.ManglikSupabase?.client) return;

  const people = [
    { id:'arjun', name:'Arjun Malhotra', initials:'AM', age:29, city:'Gurugram', profession:'Product Manager', score:96, tone:'tone-saffron', online:true, verified:true, type:['suggested','mutual','viewed'], interests:['Travel','Books'], values:['Family-first','Curious'], preferences:'Shared intention', distance:'18 km away', bio:'Warm, intentional, and fond of long walks after a great cup of coffee.' },
    { id:'vihaan', name:'Vihaan Kapoor', initials:'VK', age:31, city:'New Delhi', profession:'Architect', score:93, tone:'tone-plum', online:false, verified:true, type:['suggested','pending','viewed'], interests:['Design','Music'], values:['Kindness','Balance'], preferences:'Aligned timeline', distance:'12 km away', bio:'An architect with an eye for quiet detail, old neighbourhoods and sincere conversation.' },
    { id:'kabir', name:'Kabir Singh', initials:'KS', age:28, city:'Chandigarh', profession:'Civil Engineer', score:89, tone:'tone-sage', online:true, verified:false, type:['suggested','pending'], interests:['Cooking','Cycling'], values:['Honesty','Family'], preferences:'Manglik match', distance:'247 km away', bio:'Grounded and close to family, with a soft spot for a home-cooked meal.' },
    { id:'ishaan', name:'Ishaan Verma', initials:'IV', age:27, city:'Pune', profession:'Software Engineer', score:87, tone:'tone-blue', online:false, verified:true, type:['suggested','favorites'], interests:['Tennis','Podcasts'], values:['Growth','Warmth'], preferences:'Shared lifestyle', distance:'1,182 km away', bio:'Curious, dependable and happiest around people who enjoy a little everyday laughter.' },
    { id:'dev', name:'Dev Shah', initials:'DS', age:32, city:'Ahmedabad', profession:'Entrepreneur', score:85, tone:'tone-saffron', online:false, verified:true, type:['mutual','favorites','viewed'], interests:['Reading','Food'], values:['Tradition','Ambition'], preferences:'Open to relocate', distance:'940 km away', bio:'A practical romantic with deep roots, a growth mindset and time for the right person.' },
    { id:'samar', name:'Samar Joshi', initials:'SJ', age:26, city:'Jaipur', profession:'Doctor', score:82, tone:'tone-blue', online:true, verified:true, type:['viewed'], interests:['Music','Fitness'], values:['Care','Respect'], preferences:'Shared language', distance:'279 km away', bio:'Kind, calm and genuinely interested in a partnership built with patience.' }
  ];

  const views = {
    suggested: { eyebrow:'Picked for you', title:'Suggested matches', copy:'Profiles selected for their alignment with what matters to you.' },
    pending: { eyebrow:'Interest waiting for you', title:'Pending likes', copy:'People who would like to get to know you better.' },
    mutual: { eyebrow:'A shared yes', title:'Mutual matches', copy:'You both expressed interest — a good moment to start a conversation.' },
    favorites: { eyebrow:'Saved with intention', title:'Favorites', copy:'The profiles you wanted to keep close while you decide.' },
    viewed: { eyebrow:'Recent activity', title:'Recently viewed', copy:'Profiles you have explored recently.' }
  };
  const state = { view: window.location.hash.replace('#','') || 'suggested', saved:new Set(['ishaan','dev']), liked:new Set(['arjun','dev']), passed:new Set(), sort:'score', active:null };
  const $ = (selector, scope=document) => scope.querySelector(selector);
  const $$ = (selector, scope=document) => Array.from(scope.querySelectorAll(selector));
  let toastTimer;
  function showToast(message) { const toast=$('#matches-toast'); toast.textContent=message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('show'),3000); }
  function currentPeople() { let list=people.filter((person)=>person.type.includes(state.view) && !state.passed.has(person.id)); if(state.view==='favorites') list=people.filter((person)=>state.saved.has(person.id) && !state.passed.has(person.id)); return [...list].sort((a,b)=>state.sort==='score'?b.score-a.score:a.name.localeCompare(b.name)); }
  function cardAction(person, action, text, primary='') { const active=(action==='like'&&state.liked.has(person.id))||(action==='save'&&state.saved.has(person.id)); return `<button class="match-action ${primary} ${active?'active':''}" type="button" data-match-action="${action}" data-person-id="${person.id}" aria-label="${text} ${person.name}">${text}</button>`; }
  function card(person) { return `<article class="match-card" data-match-card="${person.id}"><div class="match-visual ${person.tone}">${person.online?'<span class="match-online"><i></i>Online</span>':'<span class="match-online">Recently active</span>'}<span class="match-score">${person.score}%</span><span class="match-initials">${person.initials}</span></div><div class="match-card-body"><div class="match-name"><h3>${person.name}, ${person.age}</h3>${person.verified?'<span class="match-verified">✓</span>':''}</div><p class="match-meta">${person.city} · ${person.profession} · ${person.distance}</p><div class="compatibility-row"><span>${person.interests[0]}</span><span>${person.values[0]}</span><span>${person.preferences}</span></div><div class="match-widget"><div><small>Shared interests</small><strong>${person.interests.join(', ')}</strong></div><div><small>Shared values</small><strong>${person.values.join(', ')}</strong></div><div><small>Mutual preferences</small><strong>${person.preferences}</strong></div><div><small>Distance</small><strong>${person.distance}</strong></div></div></div><div class="match-actions">${cardAction(person,'view','View','primary')}${cardAction(person,'like','♡')}${cardAction(person,'pass','×')}${cardAction(person,'save','⌑')}${cardAction(person,'message','✉')}</div></article>`; }
  function updateCounts() { $('#suggested-count').textContent=people.filter((person)=>person.type.includes('suggested')&&!state.passed.has(person.id)).length; $('#pending-count').textContent=people.filter((person)=>person.type.includes('pending')&&!state.passed.has(person.id)).length; $('#mutual-count').textContent=people.filter((person)=>person.type.includes('mutual')&&!state.passed.has(person.id)).length; $('#pending-tab-count').textContent=people.filter((person)=>person.type.includes('pending')&&!state.passed.has(person.id)).length; }
  function render() { if(!views[state.view]) state.view='suggested'; const view=views[state.view]; $('#match-view-eyebrow').textContent=view.eyebrow; $('#match-view-title').textContent=view.title; $('#match-view-copy').textContent=view.copy; const list=currentPeople(); $('#match-grid').innerHTML=list.map(card).join(''); $('#matches-empty').hidden=list.length!==0; $$('.match-tab').forEach((tab)=>{const active=tab.dataset.matchView===state.view;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));}); updateCounts(); window.location.hash=state.view; }
  function openDrawer(person) { state.active=person; $('#match-drawer-content').innerHTML=`<div class="drawer-profile"><div class="match-visual drawer-visual ${person.tone}"><span class="match-score">${person.score}%</span><span class="match-initials">${person.initials}</span></div><h2>${person.name}, ${person.age} ${person.verified?'<span class="match-verified">✓</span>':''}</h2><p>${person.city} · ${person.profession} · ${person.distance}</p><div class="drawer-compatibility"><strong class="drawer-ring">${person.score}%</strong><div><strong>Strong compatibility</strong><span>Based on shared values, interests, preferences and profile intention.</span></div></div><p>${person.bio}</p><div class="drawer-reasons"><div><small>Shared interests</small><strong>${person.interests.join(' · ')}</strong></div><div><small>Shared values</small><strong>${person.values.join(' · ')}</strong></div><div><small>Mutual preferences</small><strong>${person.preferences}</strong></div></div><div class="drawer-actions">${cardAction(person,'like',state.liked.has(person.id)?'Liked':'Like')}${cardAction(person,'save',state.saved.has(person.id)?'Saved':'Save')}${cardAction(person,'message','Message','primary')}${cardAction(person,'pass','Pass')}</div></div>`; $('#match-drawer').classList.add('open');$('#match-drawer-backdrop').classList.add('open');$('#match-drawer').setAttribute('aria-hidden','false'); }
  function closeDrawer() { $('#match-drawer').classList.remove('open');$('#match-drawer-backdrop').classList.remove('open');$('#match-drawer').setAttribute('aria-hidden','true'); }
  function refreshAfterAction(person) { render(); if(state.active?.id===person.id&&!state.passed.has(person.id)) openDrawer(person); else if(state.passed.has(person.id)) closeDrawer(); }
  function handleAction(button) { const person=people.find((item)=>item.id===button.dataset.personId); if(!person) return; switch(button.dataset.matchAction){case 'view':openDrawer(person);break;case 'like':state.liked.has(person.id)?state.liked.delete(person.id):state.liked.add(person.id);showToast(state.liked.has(person.id)?`${person.name} added to your likes.`:`${person.name} removed from your likes.`);refreshAfterAction(person);break;case 'save':state.saved.has(person.id)?state.saved.delete(person.id):state.saved.add(person.id);showToast(state.saved.has(person.id)?`${person.name} saved to favorites.`:`${person.name} removed from favorites.`);refreshAfterAction(person);break;case 'pass':state.passed.add(person.id);showToast(`${person.name} removed from this view.`);refreshAfterAction(person);break;case 'message':window.location.href='messages.html';break;default:break;} }
  function initialiseEvents() { $$('.match-tab').forEach((tab)=>tab.addEventListener('click',()=>{state.view=tab.dataset.matchView;render();})); $('#match-grid').addEventListener('click',(event)=>{const button=event.target.closest('[data-match-action]');if(button)handleAction(button);}); $('#match-drawer').addEventListener('click',(event)=>{const button=event.target.closest('[data-match-action]');if(button)handleAction(button);}); $('#match-drawer-close').addEventListener('click',closeDrawer);$('#match-drawer-backdrop').addEventListener('click',closeDrawer); $('#match-sort').addEventListener('click',()=>{state.sort=state.sort==='score'?'name':'score';$('#match-sort').textContent=state.sort==='score'?'Best compatibility ▾':'Name A–Z ▾';render();}); $('#matches-mobile-menu').addEventListener('click',()=>{const sidebar=$('#matches-sidebar');const open=sidebar.classList.toggle('open');$('#matches-mobile-menu').setAttribute('aria-expanded',String(open));}); document.addEventListener('keydown',(event)=>{if(event.key==='Escape')closeDrawer();}); }
  /* Future Supabase match workflow. No database queries or subscriptions run here yet. */
  window.matchesDataAdapter={getSuggestedQuery(){return{table:'match_suggestions',select:'id, user_id, suggested_profile_id, compatibility_score, shared_interests, shared_values, mutual_preferences, distance_km, created_at, profiles!match_suggestions_suggested_profile_id_fkey(*)',filters:{user_id:'current-user'},order:{column:'compatibility_score',ascending:false}};},getActionRequest(profileId,action){return{table:'match_actions',values:{target_profile_id:profileId,action}};},getFavoritesQuery(){return{table:'match_actions',select:'target_profile_id, profiles(*)',filters:{action:'save',user_id:'current-user'}};},subscribe(client,userId,onMatch){return client.channel(`matches:${userId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'match_suggestions',filter:`user_id=eq.${userId}`},onMatch).subscribe();}};
  render();initialiseEvents();
}());
